show_json_schema:
    pattern: /schemas/{alias}.json
    defaults: { _controller: json_schema.controller:showAction }

index_json_schema:
    pattern: /schemas.json
    defaults: { _controller: json_schema.controller:indexAction }
